on: push
name: Test
jobs:
  testWithTox:
    name: Test with tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test with tox
      uses: njzjz/actions/tox-conda@master
